version: 0.1 # do not change it
Settings:
  RabbitSpawnInChunkLuck: 40
  RabbitSpawnLuck: 70
  MonsterSpawnLuck: 1
  IgnoreWorlds: freebuild/mini-games
  IgnoreRegions: spawn
Msg:
  prefix: '§f[§5Easter§f]>§5 '
  no_permission: '&4ERROR &9&l> &r&bYou don''''t have permission to do that!'
  command_use: '§9[§4tr-Easter§9]> §r§cCommand use: §6$command'
  bunnyName: '&5Easter bunny'

# the percent addition need to be equals to 100
items:
  20lvls:
    levels: 20
    playerMsg: This easter bunny have 20lvls for you
    percent: 100
